server:
  port: 8080

elasticsearch:
  host: localhost
  port: 9200

service:
  datakick:
    url: https://www.datakick.org/api/items
  spoonacular:
    url: https://api.spoonacular.com
    apiKey: 1d99ae7535a64ab0a2357a46bfd37582

management:
  endpoint:
    info:
      enabled: true
    health:
      show-details: always

info:
  app:
    name: Elastictest App
    version: 0.0.1
    description: Spring Boot app using Elasticsearch Rest High Level Client from version 7.3.2
