server:
  port: 8080

elasticsearch:
  host: localhost
  port: 9200

service:
  datakick:
    url: https://www.datakick.org/api/items

management:
  endpoint:
    info:
      enabled: true

info:
  app:
    name: Elastictest App
    version: 0.0.1
    description: Spring Boot app using Elasticsearch Rest High Level Client from version 7.3.2
